### PR TITLE
Allowed disaeses to be posted with category name/pk instead only pk.

### PR DESCRIPTION
**Pull request by PazBazak**
Also displays the category name instead of pk.

### CODE REVIEW

**Comment by PazBazak** [comment]
Both eas-28 and 30 in this PR

**Comment by milimetron** [comment]
Code works really well good job!
However, we should make the repeating code to either a function or better yet create a custom class that the serializes inherit from, and pass the appropriate code

**Review by milimetron — CHANGES_REQUESTED** [review]
As said in my general comment

**Comment by milimetron** [comment]
Please Rebase this and merge :)

**Pull request merged**
